---
- name: Setup Ansible control node
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Create a new user
      user:
        name: "{{ ansible_user }}"
        password: "{{ ansible_password | password_hash('sha512') }}"
        shell: /bin/bash
        update_password: on_create

    - name: Add the new user to sudoers file
      copy:
        dest: /etc/sudoers.d/{{ ansible_user }}
        content: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'
      become: yes

    - name: Enable password authentication in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
      notify: restart sshd

    - name: Generate SSH key for the new user
      ansible.builtin.openssh_keypair:
        path: /home/{{ ansible_user }}/.ssh/id_rsa
        type: rsa
        size: 2048
        state: present
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: yes

    - name: Create ansible.cfg file
      copy:
        dest: /etc/ansible/ansible.cfg
        content: |
          [defaults]
          inventory = /etc/ansible/hosts
          remote_user = {{ ansible_user }}
          private_key_file = /home/{{ ansible_user }}/.ssh/id_rsa
          host_key_checking = False
          log_path = /var/log/ansible.log
          timeout = 30
          [privilege_escalation]
          become = True
          become_method = sudo
          become_user = root
          become_ask_pass = False
      notify: restart ansible

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
    - name: restart ansible
      service:
        name: ansible
        state: restarted
