---
- name: YUM Package Update on RHEL
  hosts: all
  become: true
  tasks:
    - name: YUM Package Update
      yum:
        name: '*'
        state: latest
      register: yum_update_result

    - name: Check if restart is required
      command: needs-restarting -r
      register: restart_required
      changed_when: false

    - name: Restart if required
      command: shutdown -r +1 "Ansible YUM update requires restart"
      async: 0
      poll: 0
      ignore_errors: true
      when: restart_required.rc == 0

    - name: Wait for the server to come back online
      local_action: wait_for
      args:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 60
        timeout: 600
        connect_timeout: 5

    - name: Check status after updates
      command: yum check-update
      register: yum_check_result

    - name: Create log file
      copy:
        content: |
          YUM update status: {{ yum_update_result }}
          Restart required: {{ 'Yes' if restart_required.rc == 0 else 'No' }}
          YUM check status: {{ yum_check_result }}
        dest: /var/log/ansible/ansible-yum-update-{{ inventory_hostname }}.log
