---
- name: Update Debian packages
  hosts: all
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      register: update_cache

    - name: Upgrade packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
      register: upgrade_packages

    - name: Check if restart is required
      command: checkrestart
      register: restart_check
      ignore_errors: yes

    - name: Restart if required
      reboot:
        msg: "Rebooting to apply updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: restart_required.stdout != ""

    - name: Wait for server to come back online
      wait_for_connection:
        delay: 5
        timeout: 300

    - name: Check status after update
      shell: dpkg -l
      register: check_status

    - name: Create log file for each step
      ansible.builtin.copy:
        content: "{{ ansible_run_result | to_nice_json }}"
        dest: /tmp/ansible-debian-package-update.log
